# GitHub Release configuration
changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - dependabot
  categories:
    - title: 🚀 Features
      labels:
        - feature
        - enhancement
    - title: 🐛 Bug Fixes
      labels:
        - bug
        - fix
    - title: 🔧 Maintenance
      labels:
        - chore
        - dependencies
    - title: 📚 Documentation
      labels:
        - documentation
    - title: 🎨 UI/UX Improvements
      labels:
        - ui
        - ux
    - title: ⚡ Performance
      labels:
        - performance
    - title: Other Changes
      labels:
        - "*"